name: cjwatson-test-godd
version: "1.0"
summary: Simple dd like tool
description:
 Written in go with support for device auto-detection via libgudev,
 you would need to use hw-assign to access devices.
architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  cjwatson-test-godd:
    command: bin/godd

parts:
  cjwatson-test-godd:
    plugin: go
    source: https://github.com/mvo5/godd
    source-type: git
    go-importpath: github.com/mvo5/godd
    stage-packages: [libgudev-1.0-dev]
    override-build: |
      # the horror the horror
      sudo mv /usr/bin/go /usr/bin/go.system
      sudo ln -s /snap/bin/go /usr/bin/go
      snapcraftctl build
      sudo rm /usr/bin/go
      sudo mv /usr/bin/go.system /usr/bin/go
    build-snaps:
      - go
    prime:
     - usr/lib/*/libgudev-1.0.so*
     - usr/lib/*/libobject-2.0.so*
     - usr/lib/*/libglib-2.0.so*
     - bin/godd*
